language: generic 
sudo : required
services:
    - docker

# Series of commands before we run our test / deploy project
before_install:
    - docker build -t schawan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true schawan/docker-react npm run test